# Generated by Django 2.2 on 2020-01-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tourist', models.BooleanField(default=False)),
                ('is_guide', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('city', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('birth_date', models.DateField(null=True, verbose_name='birth date')),
                ('avatar', models.ImageField(upload_to='images/')),
                ('date_joined', models.DateField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
