# Generated by Django 2.2 on 2020-01-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user',
        ),
    ]
