# Generated by Django 2.2 on 2020-01-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_guide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='guide',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Trip.Guide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourplan',
            name='guide',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Trip.Guide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='guide',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='Trip.Guide'),
            preserve_default=False,
        ),
    ]
